AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Super simple basic sam template
Parameters:
  Parameter1:
    Type: String
    Description: first parameter

Resources:
  LambdaExecutionRole:
      Type: "AWS::IAM::Role"
      Properties:
        ManagedPolicyArns:
         - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: "sts:AssumeRole"
        Path: "/"
        Policies:
          - PolicyName: sample_inline_policy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - "s3:GetObject"
                  Resource:
                    - !Sub "arn:aws:s3:::mytestbucket/*" 
  
  LambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./src
      Description: ''
      MemorySize: 128
      Timeout: 20
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          PARAMETER1: !Ref Parameter1
